homironi/homimemo

- src/app/globalElement.css
- src/components/Article/Article.module.css
- src/components/Article/Article.tsx
||default|dark|
|--|--|--|
|default|![image](https://github.com/user-attachments/assets/41101008-2c58-4f1f-888d-f7f98ced4a20)|![image](https://github.com/user-attachments/assets/a1e04e21-ee11-4f51-864f-176904e5f4da)|
|tablet|![image](https://github.com/user-attachments/assets/2c3e3dae-4eba-4587-b324-03fb8e859526)|![image](https://github.com/user-attachments/assets/d0005e6c-d0c1-47a2-9593-4d3f9d1f4036)|
|mobile|![image](https://github.com/user-attachments/assets/1c23e8b9-89e8-4577-9614-4da7998f9ed7)|![image](https://github.com/user-attachments/assets/48e45095-dda7-452c-b0a8-e1bb38c03e0f)|
> [update] 記事の配置スタイル設定

- src/app/globalElement.css
- src/components/Article/Article.tsx
- src/components/BreadCrumbs/Breadcrumbs.module.css
- src/components/BreadCrumbs/Breadcrumbs.stories.tsx
- src/components/BreadCrumbs/Breadcrumbs.tsx
- src/components/BreadCrumbs/index.ts
- src/components/Footer/Footer.stories.tsx
- src/components/Header/Header.stories.tsx
> [update] 記事ページにパンくずリスト追加

- src/components/Article/Article.tsx
- src/components/ArticleCategory/ArticleCategory.stories.tsx
- src/components/ArticleCategory/ArticleCategory.tsx
- src/components/ArticleCategory/index.ts
> [update] 記事にカテゴリ表示を追加

- README.md
- package.json
- buildコマンドで先に最初だけJSONが出力されるように調整
- 変更がないと最初出力されないことに気付いていなかったので修正
- ついでにREADMEも更新
> [update] buildコマンドで先に最初だけJSONが出力されるように調整

- src/components/H3/H3.module.css
- src/components/H3/H3.stories.tsx
- src/components/H3/H3.tsx
- src/components/H3/index.ts
- src/components/server/Article/Article.tsx
> [add] H3Component追加

- src/components/ArticleTags/ArticleTags.module.css
- src/components/ArticleTags/ArticleTags.stories.tsx
- src/components/ArticleTags/ArticleTags.tsx
> [update] タグが空のときの見た目設定

- src/app/globals.css
- pの行間調整
- ul,olのpaddingとmargin0に設定
> [update] globalスタイルの調整

- src/app/globals.css
- src/components/server/Article/list.css
- src/lib/server/rehypePlugins/gfmTaskList/index.css
> [update] チェックリストのネスト対応

- src/app/layout.tsx
- src/components/ShareButtons/ShareButtons.tsx
- src/lib/utils/utils.ts
> [update] titleのtemplate関数を用意してそれに置き換え

- wrangler.jsonc
https://developers.cloudflare.com/workers/configuration/routing/custom-domains/#set-up-a-custom-domain-in-your-wrangler-configuration-file
> [update] カスタムドメインを設定

- src/app/page.tsx
> [update] トップページに更新履歴を表示するように

- public/ads.txt
- https://support.google.com/adsense/answer/12171612?hl=ja&visit_id=638929393345491296-2173280057&rd=1
> [add] ads.txtを追加

- eslint.config.mts
- https://eslint.style/rules/quotes
- https://eslint.style/rules/semi
> [update] ESLintの設定を更新

- src/components/ExternalLink/ExternalLink.module.css
- src/components/ExternalLink/ExternalLink.tsx
- src/components/Favicon/Favicon.module.css
- src/components/Favicon/Favicon.stories.tsx
- src/components/Favicon/Favicon.tsx
- https://zenn.dev/irusiru/articles/d34a1bb89d7e32
> [update] 記事のリンクにfaviconを表示するように変更

- src/app/layout.tsx
- src/components/server/Article/AdSense/AdSense.tsx
- src/components/server/Article/AdSense/index.ts
- src/components/server/Article/AdSenseHandler/AdSenseHandler.tsx
- src/components/server/Article/AdSenseHandler/index.ts
- src/components/server/Article/Article.tsx
- src/components/server/Article/ArticleH2/ArticleH2.tsx
- src/components/server/Article/ArticleH2/index.ts
自動広告だと表示位置を制御しにくい（除外エリア設定もプレビューが効かなくてできない）ので、手動で広告を出す
> [add] AdSense広告を追加 (#570)

- README.md
https://developers.cloudflare.com/workers/platform/built-with-cloudflare/
> [update] CloudflareのボタンをREADMEに追加

- src/app/page.module.css
- src/app/page.tsx
- src/data/notice.tsx
- src/data/recommendedArticle.ts
> [update] TOPの表示を更新

- src/components/ErrorPage/ErrorPage.module.css
- src/components/ErrorPage/ErrorPage.stories.tsx
> [update] エラーページでsvgの色やサイズを再指定

- _contents/articles/20250525201955.md
- _contents/articles/20250525201956.md
- _contents/articles/20250525202002.md
- _contents/articles/20250525202003.md
- _contents/articles/20250525202005.md
- _contents/articles/20250525202006.md
- src/components/server/Article/prism.css
- src/lib/server/rehypePlugins/code/index.ts
> [update] Codeblockでtxtなど何もつけなくてもコードブロックの表示がされるように調整

- tsconfig.json
- wrangler.jsonc
- https://developers.cloudflare.com/workers/wrangler/configuration/
> [update] config更新

- package.json
- tsconfig.json
- https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22defaults+and+fully+supports+es6-module%22%2C%0A++%22maintained+node+versions%22%0A%5D
> [update] config調整
